### ISSUE TITLE
Replace absl-py by python stdlib and argparse

### ISSUE THREAD

**Issue by 4383** [sourcerer-io/anishot#5]
Hi!

I would to propose to you to reduce your project dependencies by replacing absl-py (gflag) by [argparse](https://docs.python.org/3/library/argparse.html) who is part of the python standard library.

Argparse is a great module and it can make the job efficiently without using a third dependency just for parsing script arguments.

Do you agree?

If you are ok with this I can easily implement it.

Give me your feedback please :)

**Comment by sergey48k** [comment]
Hi, I think it's a good idea. I normally use Google flags because I am used to them from the times I worked there. But it's not a good reason to have an extra dependency.
