### ISSUE TITLE
'Can't find matching distribution' error when installing with pip on Windows 10

### ISSUE THREAD

**Issue by willtheorangeguy** [sourcerer-io/anishot#9]
I have taken an interest in this project and was trying to install it on my local Windows 10 machine using `pip`  on **Python 3.7.0b3**.

After typing the exact command on the repo `$ pip install anishot` in Command Prompt, I got the following error message: 
```
Collecting anishot...
Could not find a version that satisfies the requirement anishot (from versions: )
No matching distribution found for anishot
````
To double-check, I checked the [PyPI](https://pypi.org/search/?q=anishot) website, and found that there was no result for _anishot_.
Could it be that the latest version was never uploaded to PyPI, or am I reading the installation instructions wrong?

**Comment by sergey48k** [comment]
Hi William,

We are still yet to release to PyPI, which should happen this week.

I apologize for the inconvenience. For now, you can clone the repo and do:

pip install pbr
python setup.py build
python setup.py install

Best,
Sergey

**Comment by willtheorangeguy** [comment]
Thanks a lot!
